### PR TITLE
Adding simple support for Raiffeisen Schweiz MT940 files. 

### PR DESCRIPTION
**Pull request by jicka**
Based on ZKB importer.

### CODE REVIEW

**Comment by tarioch** [comment]
Thank you very much for your contribution, would you mind having a look at the failing pre commit checks.

**Comment by jicka** [comment]
Thank you for maintaining these files !
I do not have experience with linting. I hope that I could fix the errors in the pre-commit checks. Let me know if it is not the case.

**Comment by tarioch** [comment]
There still seems something not fully working.

**Comment by jicka** [comment]
OK I found one last issue in my markdown. Hope this fixes all the issues :)

**Comment by tarioch** [comment]
Unfortunately still fails. Can you maybe just install pre commit locally and run it?

Should be a simple 

pip install pre-commit

And then you run

pre-commit run --all-files

**Comment by jicka** [comment]
I did not know I could do that ! (it seems obvious in hindsight...).
Thank you for the guidance. When run locally blacken-docs fixes the formatting. It was missing a line break that was not necessary on the ZKB entry I copied as it was shorter.
Pre-commit ran successfully locally.
Warm  Regards,
Jonas

**Comment by tarioch** [comment]
All good now, thank you very much will create a new release

**Pull request merged**
